version: 2

defaults: &defaults
  working_directory: ~/app

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: get-yarn
          command: sudo npm install -g yarn
      - restore_cache: # Get cache based on node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build

  lint:
    <<: *defaults
    docker:
      - image: circleci/node
    requires:
      - build
    steps:
      - checkout
      - restore_cache: # Get cache based on node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint

  test:
    <<: *defaults
    docker:
      - image: circleci/node
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_DB: test
          COVERALLS_REPO_TOKEN: DPyCMcA68lYInoY8o8aV4eJXB6z8YpG7m
    notify:
      webhooks:
        - url: https://coveralls.io/webhook?repo_token=<<DPyCMcA68lYInoY8o8aV4eJXB6z8YpG7m>>
    steps:
      - checkout
      - restore_cache: # Get cache based on node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn coverage --collectCoverage=true
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  lint-and-test:
    jobs:
      - build
      - test
      - lint
